name: Deploy README to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not `main`
  pull_request:
    branches:
      - main  # Change this to your default branch if it's not `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Convert readme.md to HTML
      run: |
        mkdir -p output
        pandoc readme.md -f markdown -t html -s -o output/index.html

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
